//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alan_mvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class nds
    {
        public string name { get; set; }
        public Nullable<decimal> c1 { get; set; }
        public Nullable<decimal> c2 { get; set; }
        public Nullable<decimal> c3 { get; set; }
        public Nullable<decimal> c4 { get; set; }
        public Nullable<decimal> c5 { get; set; }
        public Nullable<decimal> c6 { get; set; }
        public Nullable<decimal> c7 { get; set; }
        public Nullable<decimal> c8 { get; set; }
        public Nullable<decimal> c9 { get; set; }
        public Nullable<bool> myis { get; set; }
        public Nullable<int> time { get; set; }
        public short id { get; set; }
    }
}
