//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alan_mvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class ocenkas
    {
        public string name { get; set; }
        public Nullable<bool> myis { get; set; }
        public short id { get; set; }
        public Nullable<short> id1 { get; set; }
    }
}
